# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aurora's Book
email: aurorasbookcontact@gmail.com
version: 0.0.1
description: >- # this means to ignore newlines until "baseurl:"
  Hello and welcome to my blog and website. Here I talk about what is happen in
  my world. I probably will talk about chemsitry, astronomy, nature, and more.
baseurl: "/"
url: "https://aurorasbook.com"
markdown: kramdown

minima:
  social_links:
    github: aurorasbook
    twitter: aurora_powel

# site analytics
google_analytics: UA-155094288-1

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".

exclude:
  - CODE_OF_CONDUCT.md
  - README.md
  - CONTRIBUTING.md
  - .github\ISSUE_TEMPLATE\bug_report.md
  - .github\ISSUE_TEMPLATE\feature_request.md
  - .github\ISSUE_TEMPLATE\other.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  # Excluded items can be processed by explicitly listing the directories or
  # their entries' file path in the `include:` list.
